### ISSUE TITLE
Playwright don't work with Fedora, so Devika doesn't work in Fedora

### ISSUE THREAD

**Issue by Jmzp** [stitionai/devika#172] opened 2024-03-26 19:22 UTC
Hi

This issue is to ask for any alternative to Playwright to use Devika with other Linux distributions

Regards

**Comment by ibndias** [comment] 2024-03-27 01:36
duplicate of https://github.com/stitionai/devika/issues/127

**Closed** 2024-04-03 18:50 UTC
